### PR TITLE
Readd hold enabled effect

### PR DESCRIPTION
**Pull request by ko1nksm**
I don't know why you removed this, but I tried to re-implement it. What do you think?

https://github.com/ContentsViewer/sh-tetris/issues/55#issuecomment-1001170402

> This feature has been removed. It was difficult to get the same look in no-color mode.

### CODE REVIEW

**Comment by ContentsViewer** [comment]
It is difficult to explain...

In no-color mode, disabled cell have to use except '[]' because the active cell using '[]'.
The dense of '[]' is so thin (not filled) than the others(e.g.,  ░░, █) that players may misunderstand an inactive cell as active.

**Comment by ko1nksm** [comment]
I see. How about using a different symbol?

`{}`、`/]`、`[/`、`_]`、`[_`

There may be better characters in Unicode. 🤔

**Comment by ContentsViewer** [comment]
`_]` looks good when no-color mode.

**Comment by ko1nksm** [comment]
Fixed.

**Comment by ContentsViewer** [comment]
Beautiful.

**Pull request merged**
