### PR TITLE
Add option `--no-freeze` and flag `freeze_on`

### PR DESCRIPTION
**Pull request by eggplants**
https://user-images.githubusercontent.com/42153744/147396576-6c3e0eea-b715-4f5f-90ee-c31b471e4998.mov

### CODE REVIEW

**Comment by ContentsViewer** [comment]
Thank you for your PR.

But I think animation-delay is embedded in game not optional.

In other games (e.g., Puto-Puyo-Tetris, Tetris99, [tetris.com](https://tetris.com/play-tetris) ), Players can' t turn off the animation-delay, although the guidelines don't specify it.

In the case of [tetris.com](https://tetris.com/play-tetris), Players can turn off animation-effects but not animation-delay.

**Comment by eggplants** [comment]
I usually play [jstris](https://jstris.jezevec10.com/).
I prefer them to fast-response style like jstris...

**Comment by ContentsViewer** [comment]
OK.
It seems to have something to do with the game modes, so let's decide how to implement it before the next release (v2.3.0?).

**Comment by eggplants** [comment]
Thank you for your consideration so much...

**Pull request closed without merging**
