### PR TITLE
Additional shell supported

### LINKED ISSUE #7: `local` is not available on POSIX sh
`local` is not available on POSIX sh.
So, if you want to improve compatibility, consider removing them.

### PR DESCRIPTION
**Pull request by ko1nksm**
**This is a PR for review. It contains multiple commits, so don't just merge it in.**

- ksh support
- ~~zsh support~~

See #7 for details.

If you want to merge, please let me know so I will rebase.

Close #7

### CODE REVIEW

**Comment by ContentsViewer** [comment]
I want to merge these PRs (#3, #4, #5, #7) separately.

**Comment by ko1nksm** [comment]
Do you want to merge this PR first? I'm thinking of rebasing this PR later as it will definitely conflict with those (#3, #4, #5).

**Comment by ContentsViewer** [comment]
>  I'm thinking of rebasing this PR later as it will definitely conflict with those.

OK. Dont worry.

I'm planning to merge the PRs (#3, #4, #5) separately, then merge this PR.

It's going to take some time to decide to merge this PR.

**Comment by ko1nksm** [comment]
I will change this PR to ksh support only. (See #14)

**Comment by ContentsViewer** [comment]
This pull request may allow the tetris to run the Solaris OS.

**Comment by ContentsViewer** [comment]
Could you please rebase it?

**Comment by ko1nksm** [comment]
I have created a new PR (#20).

**Pull request closed without merging**
