### PR TITLE
Fix shell compatibility issues

### PR DESCRIPTION
**Pull request by ko1nksm**
Fixed various shell compatibility issues.

- Use POSIX mode to reduce differences in behavior
- Fixed issues related signals in ksh
- Improved initialization and cleanup process
- ~~Clear key buffer on exit~~ Removed because WSL1 freezes. 
  - It is not necessary if we have implemented #40.

### CODE REVIEW

**Comment by ko1nksm** [comment]
There still seems to be issues on WSL1. I'll investigate.

**Comment by ko1nksm** [comment]
The bug has been fixed, but it is not very comfortable on WSL. 😧

Please merge after #66.

**Comment by ko1nksm** [comment]
@ContentsViewer What is your test environment?

I have Windows (WSL), macOS, and Linux test environments, But I had only tested sh-tetris on macOS. 🙇

**Comment by ContentsViewer** [comment]
@ko1nksm 

It's OK!
I mainly test on Windows11 not macOS (I dont have).

* Ubuntu-18.04
  * Windows 11, WSL2
* Ubuntu-16.04
  * Windows 11, WSL1
* openSUSE-Leap-15.3
  * Windows 11, WSL2
* FreeBSD 13.0
  * Windows 11, VM
* Solaris 11
  * Windows 11, VM
* Ubuntu-20.04
  * native

**Comment by ko1nksm** [comment]
Thanks! I would like to improve the WSL response (if possible...)

**Pull request merged**
